---
title: "Vizualizacija v R"
output:
  beamer_presentation:
    incremental: no
  ioslides_presentation:
    incremental: yes
framework: io2012
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning=FALSE, out.width = "70%")
```

## Namen {.build}

- Eksploratorna analiza (identificiranje hipotez)
    - relativna primerjava
    - identificiranje vzročnosti, mehanizma vpliva, razlage
    - opazovanje več kot dveh spremenljivk
- Bolj jasna in prepričljiva predstavitev podatkov

## Sistemi za risanje {.build}

- base
    - osnoven (star) sistem
    - risanje na platno
- lattice
    - konstruiranje funkcije, ki izvede izris
- ggplot2
    - moderen pristop na osnovi določenega teoretičnega okvira
- ggvis
    - moderna nadgradnja ggvis (v izgradnji), ki uporablja spletne tehnologije

## Sistem ```ggplot2``` {.build}

- Avtor Hadley Wickham
- Moderen sistem izgrajen na praktični "teoriji" o grafiki
- Vizualizacija je preslikava iz podatkov v 2D (ali 3D) prostor z izbranim koordinatnim sistemom, in sicer v:
    - estetske atribute (barva, oblika, velikost) in
    - geometrijske objekte (točke, črte, stolpiče)
- Pametno premišljene privzete nastavitve

## Komponente ```ggplot2``` {.build}

- vhodni podatki so vedno v tabelah (```data.frame```)
- ```aes``` - estestke preslikave v barvo, obliko in velikost
- ```geoms``` - geometrijski objekti (točke, črte, liki)
- ```facets``` - izrisi pogojno na vrednosti faktorjev
- ```stats``` - statistične transformacije (delitev v koše, kvantili, glajenje)
- ```scales``` - lestvice
- koordinatni sistem

## Primeri {.build}

Glej datoteko `viri/risanje.r`
